Play/Pause video on click
webtorrent/webtorrent-desktop pull request #1878
Opened 2020-10-18 09:33 UTC by agyanttiwari

**Toggle Play/Pause on click on the player **

[x] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

2020-11-25 22:54 UTC, feross requested changes
LGTM

2020-11-25 22:54 UTC, feross commented on src/renderer/pages/player-page.js
> +      onClick={() => { state.playing.isPaused = !state.playing.isPaused }}
This should use `dispatch('playPause')`. We shouldn't modify the state from the render function, though I see that this rule is actually not being followed consistently in this file at the moment.

2021-08-16 03:58 UTC, feross approved these changes

2021-08-16 11:47 UTC, alxhotel approved these changes

2021-08-16 11:47 UTC, merged