Improve libappindicator checking
webtorrent/webtorrent-desktop pull request #1920
Opened 2021-01-31 10:30 UTC by BlueManCZ

**What is the purpose of this pull request?**
Improved functionality

**What changes did you make? (Give an overview)**
I rewrote check for `libappindicator` to work on all system, not only Debian based.

**Which issue (if any) does this pull request address?**
Closes #1399, #1851 

**Is there anything you'd like reviewers to focus on?**
I tested this only on my Gentoo system. It should work the same way everywhere else but test it, please.

A simple test without uninstalling `libappindicator` is to change `ls /usr/lib*/libappindicator*` command to something nonexistent, like `ls /usr/lib*/nonexistent*`. In the second case, the tray icon should not show.

2021-01-31 19:04 UTC, alxhotel requested changes
Hi @BlueManCZ,

Thanks for the PR!

I just tested this in my Ubuntu machine and it does not find the library. In addition, this needs permissions to access the `/usr` directory.

Please change the command to this one:

```sh
ldconfig -p | grep libappindicator
```

Check if the above command works in your Gentoo machine. If it works, then please update the PR with the change.

2021-01-31 21:27 UTC, BlueManCZ commented
Yes, this command works for me as well. Changed.

Just curious, where are those libraries located in Ubuntu?

And `/usr` directory is readable for everyone. I can't think of anyone not having access there.

2021-02-01 17:35 UTC, alxhotel commented
My libappindicator library in Ubuntu is located at `/usr/lib/x86_64-linux-gnu/libappindicator3.so.1`. That's probably why the other command doesn't work.

2021-02-01 17:36 UTC, alxhotel approved these changes

2021-02-01 17:37 UTC, merged